version: '3'

services:
  players:
    build: ./players
    ports:
      - 5002:80
    volumes:
#below the ":" binds the updates from the host to docker volume
      - ./players:/app
  site:
    build: ./site
    ports:
      - 5000:80
    depends_on:
      - players
    volumes:
      - ./site:/src





